blank_issues_enabled: true
contact_links:
  - name: "💡 Request a Feature"
    about: Request a new feature or enhancement
    url: https://github.com/cssnr/smwc-web-extension/discussions/new?category=feature-requests

  - name: "❔ Ask a Question"
    about: Ask a general question or start a discussion
    url: https://github.com/cssnr/smwc-web-extension/discussions/new?category=q-a

  - name: "💬 Join Discord"
    about: Chat with us about anything
    url: https://discord.gg/wXy6m2X8wY

  - name: "📝 Submit Feedback"
    about: Send General Feedback.
    url: https://cssnr.github.io/feedback/?app=SMWC%20Web%20Extension
