blank_issues_enabled: true
contact_links:
  - name: "🎮 SMWC World Website"
    about: Go to the SMWC World Website
    url: https://smwcworld.com/

  - name: "❔ Start a Discussion"
    about: Ask a general question or start a discussion
    url: https://github.com/cssnr/smwc-web-extension/discussions

  - name: "💬 Join Discord"
    about: Chat with us about anything
    url: https://discord.gg/wXy6m2X8wY

  - name: "🌐 View Developer Site"
    about: Visit the developers website
    url: https://cssnr.github.io/
