name: "Test"

on:
  push:
    branches: ["master"]
    paths:
      - "src/**"
      - "tests/**"
  pull_request:
    branches: ["master"]
    paths:
      - "src/**"
      - "tests/**"
  workflow_dispatch:

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: ${{ !contains(github.event.head_commit.message, '#notest') }}

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup Node"
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: "Install"
        run: |
          npm install

      - name: "Lint"
        run: |
          npm run lint
